### ISSUE TITLE
Страница редактирования профиля. 

### ISSUE THREAD

**Issue by NorthernBlow** [pooh2pooh/forum#1]
- [x] 1. Когда меняю ссылку на профиль в last.fm ломается вывод прослушанных треков. Нужно сделать валидатор формы или может быть как-то еще обыграть этот случай, либо же проверку вывода самого настроить с уведомлением пользователя о том что он написал какую-то дичь вместо имени пользователя на last.fm

- [x] 3. Когда изменяю ник на форуме, вставляя туда спецсимволы либо элементы литералов, зарезервированных слов в языке php ломаются все кнопки на этой страничке и перестают работать. в URL подставляется такая же дичь что и туда ввел.

**Comment by NorthernBlow** [comment]
компьютер **перезагружал** - не помогло. систему обновлял, в журнале ошибок не пишет.

**Comment by pooh2pooh** [comment]
1 и 3 пофикшено в коммите https://github.com/pooh2pooh/forum/commit/76e6cd6ef2475665680ac221a82058c585b617f1
